name: Run Monitor

on:
  workflow_dispatch:

jobs:
  use-env-context:
    name: APP_ENV via `env`
    runs-on: ubuntu-latest
    env:
      APP_ENV: ${{ vars.APP_ENV }}
    steps:
      - name: Print APP_ENV
        run: echo "Ambiente de aplicação: $APP_ENV"

  use-vars-context:
    name:  Email via `vars`
    runs-on: ubuntu-latest
    steps:
      - name: Print SUPPORT_EMAIL from vars
        run: echo "Suporte: ${{ vars.SUPPORT_EMAIL }}"

  use-secrets-context:
    name: API Key via `secrets`
    runs-on: ubuntu-latest
    steps:
      - name: Use secret API_KEY
        run: echo "Usando chave da API: ${{ secrets.API_KEY::0:5 }}*****"
