name: Run Monitor

on:
  workflow_dispatch:

jobs:
  use-env-context:
    name: APP_ENV via env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print APP_ENV from env
        env:
          APP_ENV: ${{ vars.APP_ENV }}
        run:  $APP_ENV

  use-vars-context:
    name: SUPPORT_EMAIL via vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print SUPPORT_EMAIL from vars
        run: ${{ vars.SUPPORT_EMAIL }}

  use-secrets-context:
    name: API_KEY via secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Confirm API_KEY usage
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo "Chave da API foi carregada com sucesso."
